module.exports = [
  {
    inputs: [
      'dcagfb',
      'cbegda',
      'cabdf',
      'bagedf',
      'dcb',
      'cd',
      'dcbegaf',
      'aebcf',
      'bgdaf',
      'dgcf',
    ],
    outputs: ['dacebgf', 'cbafd', 'dbacf', 'cdgf'],
  },
  {
    inputs: [
      'dfgbc',
      'ceagbd',
      'egb',
      'cgdae',
      'eafcgd',
      'ecbgd',
      'eb',
      'aefbgcd',
      'bfaceg',
      'deba',
    ],
    outputs: ['baed', 'ecabgd', 'aebd', 'cadfebg'],
  },
  {
    inputs: [
      'acbd',
      'bagfec',
      'bedcf',
      'efbca',
      'dbfecag',
      'gadcfe',
      'dc',
      'dbcaef',
      'cde',
      'fbegd',
    ],
    outputs: ['deacfg', 'bfagcde', 'bgedf', 'cde'],
  },
  {
    inputs: [
      'dgec',
      'dfc',
      'fabgd',
      'bfcgae',
      'dfbcg',
      'baegdcf',
      'cd',
      'fbdace',
      'cdbefg',
      'becgf',
    ],
    outputs: ['cedg', 'adfbecg', 'badgf', 'dgbfc'],
  },
  {
    inputs: [
      'be',
      'bacedg',
      'dfacb',
      'fbge',
      'deagcf',
      'eba',
      'egacf',
      'gcebfa',
      'febac',
      'dbgacfe',
    ],
    outputs: ['befg', 'be', 'egbf', 'aedgcbf'],
  },
  {
    inputs: [
      'gafbd',
      'gbafce',
      'agced',
      'fdgae',
      'bcedgaf',
      'gdeacb',
      'efdc',
      'eaf',
      'fe',
      'cgeadf',
    ],
    outputs: ['cgdae', 'fdec', 'fcdeabg', 'ef'],
  },
  {
    inputs: [
      'cdaefgb',
      'cfadbe',
      'gc',
      'afgcbe',
      'afedcg',
      'faecb',
      'cabg',
      'egc',
      'bfgde',
      'bfgce',
    ],
    outputs: ['fbaedc', 'gc', 'abgc', 'bfcea'],
  },
  {
    inputs: [
      'egcafb',
      'adgecf',
      'caebf',
      'fdgbaec',
      'fbaed',
      'cebg',
      'facbgd',
      'cfe',
      'fgabc',
      'ec',
    ],
    outputs: ['fbgca', 'deagfc', 'ce', 'ce'],
  },
  {
    inputs: [
      'fcdab',
      'deb',
      'cdbfea',
      'fecb',
      'befcdga',
      'abecd',
      'gdcae',
      'efbgda',
      'fcdgba',
      'be',
    ],
    outputs: ['cfbad', 'dacge', 'gbdeaf', 'bed'],
  },
  {
    inputs: [
      'afdecg',
      'gfcadb',
      'ecadfbg',
      'facgd',
      'ed',
      'egda',
      'efbgc',
      'ecd',
      'cdegf',
      'bfadec',
    ],
    outputs: ['becgf', 'fcbeg', 'de', 'cgefb'],
  },
  {
    inputs: [
      'caedbg',
      'gcfdba',
      'bfdae',
      'ge',
      'beagfdc',
      'bedag',
      'gcabd',
      'egac',
      'gcefbd',
      'deg',
    ],
    outputs: ['fdbecg', 'acge', 'bgfacd', 'abefd'],
  },
  {
    inputs: [
      'befad',
      'ecgad',
      'adgefcb',
      'febg',
      'gb',
      'afdcbe',
      'dcbfag',
      'beafgd',
      'dbg',
      'eagdb',
    ],
    outputs: ['feabd', 'aedfb', 'gbd', 'aebdcf'],
  },
  {
    inputs: [
      'bcfde',
      'acbfed',
      'dcaf',
      'dbcae',
      'gacbfe',
      'fc',
      'dgbcae',
      'egbacfd',
      'fcb',
      'edbfg',
    ],
    outputs: ['gbdfe', 'gbeafc', 'bcf', 'cebfga'],
  },
  {
    inputs: [
      'cgbade',
      'adcbgfe',
      'fb',
      'efgbad',
      'gbcfde',
      'aecfd',
      'edgba',
      'afbg',
      'bfeda',
      'fbe',
    ],
    outputs: ['ecafbdg', 'bfdea', 'fgab', 'edfbgc'],
  },
  {
    inputs: [
      'cbfa',
      'gefbd',
      'bcfedga',
      'bagefc',
      'ab',
      'bga',
      'ecdgab',
      'gbaef',
      'gfacde',
      'fcage',
    ],
    outputs: ['acdegf', 'gab', 'cegadb', 'gab'],
  },
  {
    inputs: [
      'cafbeg',
      'dfaebc',
      'fdca',
      'dgcbe',
      'eacbf',
      'fde',
      'debgfca',
      'egabfd',
      'dfceb',
      'fd',
    ],
    outputs: ['df', 'eabcf', 'egbdc', 'dfe'],
  },
  {
    inputs: [
      'egcdfa',
      'ebdac',
      'fdaecbg',
      'ed',
      'fdacb',
      'agecb',
      'cbdgaf',
      'ecd',
      'efdb',
      'dbaecf',
    ],
    outputs: ['dcabf', 'cbeag', 'ebdf', 'ecgba'],
  },
  {
    inputs: [
      'gacdebf',
      'decfbg',
      'afbdg',
      'dcagbf',
      'cg',
      'agdbc',
      'agcf',
      'ebcad',
      'abgedf',
      'bcg',
    ],
    outputs: ['badec', 'dcbga', 'cgfa', 'abcde'],
  },
  {
    inputs: [
      'fgcad',
      'dfebga',
      'gdbef',
      'ec',
      'ebcd',
      'fbcgea',
      'ceg',
      'fgedc',
      'defgbac',
      'dcfgbe',
    ],
    outputs: ['ce', 'gbdfe', 'fbcgdea', 'fcgbdea'],
  },
  {
    inputs: [
      'cgbef',
      'afcbeg',
      'dgbec',
      'ebafcd',
      'cgbfeda',
      'adbge',
      'cd',
      'ecd',
      'gfcd',
      'fgbdec',
    ],
    outputs: ['edc', 'gcebd', 'fegacdb', 'cd'],
  },
  {
    inputs: [
      'bafdcg',
      'egfdc',
      'bcfge',
      'dgeabf',
      'cd',
      'cgbadfe',
      'agefd',
      'facegd',
      'eadc',
      'cgd',
    ],
    outputs: ['cgd', 'dcg', 'defbagc', 'cfdbega'],
  },
  {
    inputs: [
      'degfcb',
      'fdg',
      'edabgf',
      'cadge',
      'fg',
      'gfcb',
      'cdeafbg',
      'bcefd',
      'dgfec',
      'beadcf',
    ],
    outputs: ['dgcbfe', 'cabfed', 'fecbd', 'cgdfbea'],
  },
  {
    inputs: [
      'dbfaec',
      'bfcgae',
      'cdb',
      'cdaf',
      'defbcg',
      'abgde',
      'ceabf',
      'adceb',
      'decgafb',
      'cd',
    ],
    outputs: ['fcda', 'bdc', 'dc', 'afgecb'],
  },
  {
    inputs: [
      'cead',
      'efcdg',
      'adbcfeg',
      'fagdc',
      'def',
      'acegfd',
      'fcbagd',
      'cbgef',
      'ed',
      'fgdaeb',
    ],
    outputs: ['ecad', 'fcaedg', 'cgadf', 'cfaged'],
  },
  {
    inputs: [
      'egdbfa',
      'cbgefad',
      'dgacbf',
      'cb',
      'dfbgec',
      'gefbd',
      'cbf',
      'gefbc',
      'gcefa',
      'bdec',
    ],
    outputs: ['ebcd', 'ecgdbf', 'fgebc', 'cfb'],
  },
  {
    inputs: [
      'fagbe',
      'acbged',
      'bf',
      'eagcf',
      'dgaebcf',
      'gbf',
      'febadg',
      'deabg',
      'cdagbf',
      'fbed',
    ],
    outputs: ['fbcdag', 'fgeca', 'abgdcf', 'cdbage'],
  },
  {
    inputs: [
      'baefc',
      'febgadc',
      'fcag',
      'dbgec',
      'feg',
      'gacfbe',
      'gfecb',
      'afedgb',
      'fg',
      'edafcb',
    ],
    outputs: ['aegdfb', 'feabc', 'agbfed', 'fabged'],
  },
  {
    inputs: [
      'gfedcb',
      'eadgcf',
      'fed',
      'befdagc',
      'gaedf',
      'bgdea',
      'bdafcg',
      'fe',
      'acdfg',
      'feca',
    ],
    outputs: ['bcfdga', 'cagfd', 'afce', 'efca'],
  },
  {
    inputs: [
      'cbfed',
      'degfba',
      'fgdbac',
      'acdg',
      'fdcab',
      'ac',
      'acgebf',
      'agdfb',
      'bac',
      'gcbfdea',
    ],
    outputs: ['cbdegfa', 'caefgbd', 'ca', 'gdbcafe'],
  },
  {
    inputs: [
      'dbcgea',
      'dc',
      'dcg',
      'cadf',
      'abgcdf',
      'efgdb',
      'afgbc',
      'gefacdb',
      'fbcdg',
      'agebfc',
    ],
    outputs: ['dabgce', 'gbceda', 'dgc', 'dc'],
  },
  {
    inputs: [
      'ef',
      'dgfbc',
      'cefbg',
      'gabecfd',
      'agceb',
      'feg',
      'gbcadf',
      'dfbe',
      'fcdgeb',
      'dfagec',
    ],
    outputs: ['gfe', 'cafegd', 'dfeb', 'fe'],
  },
  {
    inputs: [
      'ebgdc',
      'egdacb',
      'dfbcega',
      'dfe',
      'dbfge',
      'bagef',
      'ecdbfg',
      'bdcf',
      'df',
      'fgecad',
    ],
    outputs: ['dbgce', 'fd', 'cfdb', 'edf'],
  },
  {
    inputs: [
      'bdage',
      'ab',
      'fbgaecd',
      'aefb',
      'bfadeg',
      'gefad',
      'cdgeb',
      'agcbdf',
      'gba',
      'fgcdae',
    ],
    outputs: ['cgdbfa', 'befa', 'dgefca', 'acebfdg'],
  },
  {
    inputs: [
      'aecb',
      'dbgecf',
      'eagfcb',
      'ecdbfag',
      'fdegba',
      'geacf',
      'gebfa',
      'cge',
      'cgdfa',
      'ec',
    ],
    outputs: ['acgfe', 'gec', 'cabe', 'fgcda'],
  },
  {
    inputs: [
      'acd',
      'cafg',
      'abedcgf',
      'cfebda',
      'efcbgd',
      'cegfd',
      'ca',
      'cdgafe',
      'agcde',
      'bgeda',
    ],
    outputs: ['egcfbda', 'gcfdae', 'gefacd', 'dca'],
  },
  {
    inputs: [
      'dcefga',
      'gdefa',
      'db',
      'fbaed',
      'abefdgc',
      'faebc',
      'fbgaed',
      'bdf',
      'gbed',
      'dcafgb',
    ],
    outputs: ['bfd', 'db', 'db', 'gbdfae'],
  },
  {
    inputs: [
      'befac',
      'abcd',
      'bdcfe',
      'ecd',
      'cd',
      'baegfc',
      'edfgca',
      'adfbce',
      'aebcdgf',
      'edbfg',
    ],
    outputs: ['cgedfab', 'feabc', 'cd', 'dabc'],
  },
  {
    inputs: [
      'eacdgf',
      'cebgdfa',
      'acgebd',
      'ecdba',
      'dbcfea',
      'fdgcb',
      'dag',
      'ga',
      'acgdb',
      'abge',
    ],
    outputs: ['ag', 'ga', 'adg', 'ag'],
  },
  {
    inputs: [
      'gca',
      'fagbe',
      'dfageb',
      'bagce',
      'ecgfab',
      'gfce',
      'gc',
      'dcfeabg',
      'fadbcg',
      'bedac',
    ],
    outputs: ['afbdceg', 'gadfeb', 'cga', 'acbdfg'],
  },
  {
    inputs: [
      'gbad',
      'febac',
      'dea',
      'gadbecf',
      'fdegbc',
      'edfacg',
      'da',
      'bdecg',
      'cdbea',
      'bdcgae',
    ],
    outputs: ['dbag', 'cdeabg', 'gcdaeb', 'adbg'],
  },
  {
    inputs: [
      'cdgfeb',
      'cbeaf',
      'adef',
      'cfa',
      'fa',
      'aecbg',
      'fedcb',
      'acdebf',
      'bdcfga',
      'cdefbga',
    ],
    outputs: ['fdea', 'eadf', 'efad', 'caefb'],
  },
  {
    inputs: [
      'aedgb',
      'df',
      'cgbaed',
      'gdef',
      'bfcgda',
      'bfd',
      'efbac',
      'dgfeab',
      'debfa',
      'aegcbdf',
    ],
    outputs: ['acbfe', 'egfd', 'afebgd', 'gefd'],
  },
  {
    inputs: [
      'badcfe',
      'fcbg',
      'bf',
      'dfecbga',
      'faged',
      'gfadbc',
      'dfb',
      'dfgab',
      'abdcg',
      'dbceag',
    ],
    outputs: ['bf', 'fb', 'dafbgec', 'fbd'],
  },
  {
    inputs: [
      'bdae',
      'decgbf',
      'afcbge',
      'bdecfa',
      'afcbd',
      'edgfcab',
      'ebcaf',
      'bd',
      'dfacg',
      'dbc',
    ],
    outputs: ['ebda', 'db', 'cbd', 'cbd'],
  },
  {
    inputs: [
      'acfgde',
      'ae',
      'eac',
      'agbdec',
      'gadcb',
      'ebgcafd',
      'baed',
      'gfcbe',
      'cgabe',
      'bfgadc',
    ],
    outputs: ['cea', 'fecdga', 'ebgdac', 'eac'],
  },
  {
    inputs: [
      'cbedga',
      'cfb',
      'adcbe',
      'bfae',
      'afcdgeb',
      'cgdaf',
      'fcedab',
      'bf',
      'fcbdeg',
      'dacbf',
    ],
    outputs: ['dfceba', 'fcdga', 'fbc', 'fcebda'],
  },
  {
    inputs: [
      'cdafg',
      'dfgeac',
      'fc',
      'dbgcef',
      'gadbc',
      'gacfebd',
      'dcf',
      'edfgab',
      'gefad',
      'caef',
    ],
    outputs: ['fadgc', 'facged', 'adgefb', 'ecgbdaf'],
  },
  {
    inputs: [
      'gdcbf',
      'eabdgf',
      'gaefd',
      'fbdge',
      'afcedg',
      'bacgfe',
      'fagbedc',
      'dbea',
      'efb',
      'be',
    ],
    outputs: ['ecagfb', 'dgaef', 'be', 'eb'],
  },
  {
    inputs: [
      'gbecad',
      'faced',
      'abgedf',
      'cd',
      'cbfd',
      'abedcf',
      'dacgbfe',
      'cde',
      'deabf',
      'agcfe',
    ],
    outputs: ['cd', 'edbfac', 'cgabed', 'daebfg'],
  },
  {
    inputs: [
      'cgebaf',
      'dacbge',
      'gafed',
      'eadbgf',
      'dgcef',
      'ad',
      'fadgbce',
      'dea',
      'bgafe',
      'dafb',
    ],
    outputs: ['fegad', 'dgeaf', 'ad', 'gdfae'],
  },
  {
    inputs: [
      'ecfadb',
      'eagdbc',
      'afbcdge',
      'abfcgd',
      'cf',
      'bgedf',
      'agfc',
      'cfd',
      'gbfdc',
      'bcagd',
    ],
    outputs: ['fcga', 'fcd', 'befgd', 'gdbfc'],
  },
  {
    inputs: [
      'afcbg',
      'gfeb',
      'gfcad',
      'ecgdba',
      'cbf',
      'cafbeg',
      'bacge',
      'fb',
      'ebdfac',
      'baedcfg',
    ],
    outputs: ['fbc', 'gabce', 'egabc', 'fcadg'],
  },
  {
    inputs: [
      'agd',
      'gadbc',
      'da',
      'agcfed',
      'gcebad',
      'dgfcb',
      'ecabg',
      'ebcagdf',
      'eadb',
      'becfag',
    ],
    outputs: ['fgbeadc', 'bcega', 'geacb', 'gceab'],
  },
  {
    inputs: [
      'gaebf',
      'gfdbce',
      'aefbgd',
      'fde',
      'aefcbg',
      'ed',
      'dcaebfg',
      'agde',
      'aefdb',
      'acfdb',
    ],
    outputs: ['efd', 'agcdebf', 'cbgefd', 'ebgfa'],
  },
  {
    inputs: [
      'cdgfe',
      'ecbafd',
      'ebgca',
      'ad',
      'gedbcfa',
      'cad',
      'adbg',
      'cedabg',
      'egcad',
      'fcebga',
    ],
    outputs: ['gbedac', 'adgb', 'ecdgab', 'daceg'],
  },
  {
    inputs: [
      'efcb',
      'fcdag',
      'begdfa',
      'egcdf',
      'edf',
      'fe',
      'gfcdeb',
      'cdbega',
      'geacdbf',
      'becdg',
    ],
    outputs: ['dagfc', 'gbadef', 'decbg', 'fe'],
  },
  {
    inputs: [
      'bgaed',
      'agfdc',
      'fdgea',
      'fae',
      'fabcgd',
      'gcfe',
      'fe',
      'decfga',
      'afgedcb',
      'facbed',
    ],
    outputs: ['gdafe', 'ef', 'eacfbgd', 'fe'],
  },
  {
    inputs: [
      'ebgfca',
      'def',
      'fd',
      'ecgfbd',
      'efbda',
      'eabdg',
      'edgcfba',
      'afdc',
      'ecbfa',
      'bfdaec',
    ],
    outputs: ['abcefd', 'fd', 'dafc', 'debcagf'],
  },
  {
    inputs: [
      'eacbg',
      'efbdgca',
      'fdbga',
      'gde',
      'abecdg',
      'beagd',
      'cdeafg',
      'de',
      'cebd',
      'ecagbf',
    ],
    outputs: ['gaedbc', 'gdcbafe', 'gaecdf', 'bgdeac'],
  },
  {
    inputs: [
      'bafce',
      'cedb',
      'edacgfb',
      'fbgac',
      'fbe',
      'aedfgb',
      'be',
      'cbedfa',
      'cdefa',
      'eacfgd',
    ],
    outputs: ['be', 'acbfg', 'gfbac', 'edbc'],
  },
  {
    inputs: [
      'dgba',
      'cbgfdea',
      'gbe',
      'fbaegc',
      'cbedga',
      'fegdc',
      'decafb',
      'cdbge',
      'bg',
      'daecb',
    ],
    outputs: ['cadfbe', 'bgad', 'beadgc', 'bgedc'],
  },
  {
    inputs: [
      'abd',
      'fdbcae',
      'aedfb',
      'daec',
      'ad',
      'bacfdg',
      'dgefcb',
      'agbef',
      'cbefd',
      'cbagdef',
    ],
    outputs: ['ad', 'dab', 'acde', 'da'],
  },
  {
    inputs: [
      'cdagbe',
      'dagbe',
      'fageb',
      'gdfbeca',
      'gdcba',
      'edac',
      'dgcfba',
      'egd',
      'egcfbd',
      'ed',
    ],
    outputs: ['fbgcad', 'cafdbg', 'de', 'facbged'],
  },
  {
    inputs: [
      'dbecf',
      'egadfb',
      'cfagde',
      'da',
      'fcebga',
      'cagef',
      'dae',
      'fadec',
      'dagc',
      'dfbcaeg',
    ],
    outputs: ['da', 'dgac', 'bfedc', 'ad'],
  },
  {
    inputs: [
      'efa',
      'adcf',
      'fgcde',
      'acgeb',
      'bgedfa',
      'efcga',
      'degfbc',
      'aegcfdb',
      'fa',
      'efdgac',
    ],
    outputs: ['cfgea', 'fedgc', 'ecagf', 'efdacgb'],
  },
  {
    inputs: [
      'fecga',
      'eafgd',
      'acgefb',
      'cf',
      'gceab',
      'fbcdag',
      'gecdafb',
      'cabedg',
      'fbec',
      'gcf',
    ],
    outputs: ['agcbfd', 'gfc', 'cgf', 'ceagf'],
  },
  {
    inputs: [
      'egcaf',
      'ecdafgb',
      'dfgea',
      'cbafe',
      'dfebgc',
      'bgac',
      'cbagef',
      'cg',
      'gfc',
      'ecdfab',
    ],
    outputs: ['edbfgca', 'edafg', 'cgf', 'gfc'],
  },
  {
    inputs: [
      'afdcgb',
      'decgb',
      'fbdegca',
      'fbgae',
      'fdbaeg',
      'dgfbe',
      'gbafce',
      'df',
      'fdb',
      'efda',
    ],
    outputs: ['gcbed', 'dafe', 'gbfdca', 'aefgb'],
  },
  {
    inputs: [
      'gaebd',
      'baefg',
      'cfadbg',
      'fb',
      'gaedfbc',
      'gadbef',
      'cfgea',
      'bfde',
      'baf',
      'gacdeb',
    ],
    outputs: ['abf', 'cdbagf', 'aecbdg', 'fagec'],
  },
  {
    inputs: [
      'cfdb',
      'dcg',
      'geadbf',
      'febdg',
      'edfabcg',
      'dc',
      'bgecd',
      'eabcg',
      'fcgead',
      'cgbfde',
    ],
    outputs: ['dgc', 'dc', 'bdfge', 'dcfebga'],
  },
  {
    inputs: [
      'dfbcaeg',
      'fdgcae',
      'gfdab',
      'bagc',
      'gabcdf',
      'fecbgd',
      'cadgf',
      'gb',
      'fbade',
      'bdg',
    ],
    outputs: ['bdg', 'gacb', 'bgac', 'ecfbdg'],
  },
  {
    inputs: [
      'eg',
      'befdg',
      'fceabd',
      'badfg',
      'dbecf',
      'egbcfa',
      'bedgcf',
      'gbacefd',
      'egb',
      'dceg',
    ],
    outputs: ['beg', 'faecdb', 'gfdbe', 'dbacef'],
  },
  {
    inputs: [
      'cdagef',
      'edfca',
      'dgfa',
      'fca',
      'fa',
      'agedc',
      'gfcabe',
      'bdfec',
      'bdcage',
      'fbcaedg',
    ],
    outputs: ['caedbfg', 'ecafgbd', 'fdcega', 'decgfba'],
  },
  {
    inputs: [
      'gfc',
      'cfeb',
      'cafgdb',
      'fc',
      'aedgbfc',
      'cgdfe',
      'degfb',
      'aedcg',
      'fbegcd',
      'dfgbea',
    ],
    outputs: ['acdge', 'fedbg', 'agedc', 'ebgdfa'],
  },
  {
    inputs: [
      'aegdcb',
      'gde',
      'dgbfca',
      'eg',
      'bdecfga',
      'fedbgc',
      'gcbfd',
      'fgecd',
      'bfge',
      'acefd',
    ],
    outputs: ['ge', 'debcag', 'bgedcf', 'bfeg'],
  },
  {
    inputs: [
      'gbd',
      'eagbc',
      'cbefagd',
      'gcde',
      'aefdb',
      'gcebad',
      'cgdafb',
      'dg',
      'aegbd',
      'facbge',
    ],
    outputs: ['cdeg', 'cged', 'ebdaf', 'gbd'],
  },
  {
    inputs: [
      'eagbcf',
      'cba',
      'aebd',
      'cdfga',
      'cdegbf',
      'afcbedg',
      'dcbfe',
      'ab',
      'adfcb',
      'acfbde',
    ],
    outputs: ['bcfeag', 'fgdcbe', 'daeb', 'bdae'],
  },
  {
    inputs: [
      'gc',
      'dabcfg',
      'dcfageb',
      'acg',
      'ecabf',
      'bgadef',
      'facge',
      'gfeda',
      'ecdg',
      'fagced',
    ],
    outputs: ['gcde', 'efdga', 'agc', 'fgaed'],
  },
  {
    inputs: [
      'bcgdea',
      'bacfdg',
      'aeg',
      'cdabg',
      'dfeagc',
      'befgd',
      'aebc',
      'dabfgec',
      'ae',
      'degba',
    ],
    outputs: ['ebfdg', 'egadcf', 'aceb', 'gbdac'],
  },
  {
    inputs: [
      'ceadf',
      'defagb',
      'fg',
      'agbed',
      'dfgaebc',
      'bfaecg',
      'eacdbg',
      'afgde',
      'efg',
      'fgbd',
    ],
    outputs: ['gf', 'egbda', 'fabegc', 'badfgec'],
  },
  {
    inputs: [
      'begcfd',
      'fdecb',
      'fbdga',
      'ca',
      'bace',
      'cfadb',
      'egfdca',
      'cda',
      'cfaedb',
      'efabdcg',
    ],
    outputs: ['gacefd', 'fdgba', 'fcdebg', 'bcae'],
  },
  {
    inputs: [
      'bcga',
      'agbefc',
      'fageb',
      'ca',
      'afc',
      'debfc',
      'dafegc',
      'fdgeab',
      'abfdgec',
      'fecab',
    ],
    outputs: ['gdafceb', 'befac', 'fdecga', 'ac'],
  },
  {
    inputs: [
      'fce',
      'adcfg',
      'cgdefa',
      'bgcfda',
      'fdae',
      'acegf',
      'fe',
      'cgbae',
      'adgfceb',
      'cdegfb',
    ],
    outputs: ['gedacbf', 'fdebgac', 'deaf', 'afde'],
  },
  {
    inputs: [
      'agcf',
      'dbegf',
      'bga',
      'cfeba',
      'gfdebca',
      'fgaeb',
      'cbdefa',
      'ag',
      'egadcb',
      'cbfega',
    ],
    outputs: ['fbdge', 'gcabef', 'cagf', 'ebdafc'],
  },
  {
    inputs: [
      'aedg',
      'ge',
      'decbga',
      'bafce',
      'ecg',
      'gcdab',
      'degfcab',
      'gcfdeb',
      'ceabg',
      'abdcfg',
    ],
    outputs: ['cbfea', 'ecg', 'bafec', 'eacfb'],
  },
  {
    inputs: [
      'gfdceb',
      'cgb',
      'bcdfe',
      'gebdc',
      'egcabdf',
      'egcf',
      'bafcgd',
      'bgdae',
      'edabfc',
      'cg',
    ],
    outputs: ['gbc', 'bgdfca', 'cgfe', 'gc'],
  },
  {
    inputs: [
      'bg',
      'bedcf',
      'dgfaec',
      'fdbgc',
      'gcbafed',
      'fbg',
      'bfaged',
      'gadcf',
      'cgab',
      'acbgfd',
    ],
    outputs: ['agfbde', 'bg', 'bgcdf', 'fgb'],
  },
  {
    inputs: [
      'gafcb',
      'cdfgab',
      'abfcge',
      'cbgde',
      'bdcfae',
      'ea',
      'faeg',
      'dbgcafe',
      'ace',
      'agebc',
    ],
    outputs: ['decbaf', 'fbacde', 'bcagf', 'ace'],
  },
  {
    inputs: [
      'bgfdac',
      'cgabdef',
      'efdca',
      'fagce',
      'febagc',
      'cd',
      'fcd',
      'dfeacg',
      'gdce',
      'aefdb',
    ],
    outputs: ['dc', 'dgcfba', 'ecdagf', 'gfacbe'],
  },
  {
    inputs: [
      'bde',
      'eb',
      'egfbdc',
      'ebgfd',
      'fbdgc',
      'daebgc',
      'cagfbd',
      'gfbceda',
      'efbc',
      'aedfg',
    ],
    outputs: ['cgebadf', 'becf', 'cfbdg', 'cfbedg'],
  },
  {
    inputs: [
      'ebcdfag',
      'fadec',
      'daceg',
      'gbecaf',
      'eabcfd',
      'fd',
      'fad',
      'aebfc',
      'fcgbad',
      'efbd',
    ],
    outputs: ['dcefbag', 'fceagb', 'fdecabg', 'adf'],
  },
  {
    inputs: [
      'efgd',
      'fd',
      'bfagcd',
      'acefb',
      'febad',
      'gdbaef',
      'edcgba',
      'badge',
      'dbgaefc',
      'daf',
    ],
    outputs: ['eafbd', 'gbcdfa', 'gdfe', 'edgba'],
  },
  {
    inputs: [
      'cefdag',
      'bfagec',
      'bedcg',
      'da',
      'acd',
      'bcfead',
      'bdgcefa',
      'gcaef',
      'acdeg',
      'agfd',
    ],
    outputs: ['geacbf', 'faegdc', 'fcdgbea', 'eacgfdb'],
  },
  {
    inputs: [
      'bcedgaf',
      'bgfae',
      'cab',
      'bdcg',
      'cb',
      'gcade',
      'egdacf',
      'abdegc',
      'agbec',
      'becfad',
    ],
    outputs: ['gfcadbe', 'adgbec', 'gebfcda', 'cfaedg'],
  },
  {
    inputs: [
      'gf',
      'edbcafg',
      'cfge',
      'gdafe',
      'gdf',
      'cdabfg',
      'eabdg',
      'dgefac',
      'acfed',
      'fbceda',
    ],
    outputs: ['geabd', 'cbgdfa', 'ceadbf', 'agbfdc'],
  },
  {
    inputs: [
      'fcbgde',
      'fbged',
      'cgfdb',
      'gdebcaf',
      'cfge',
      'ebg',
      'deabf',
      'baedcg',
      'ge',
      'dfabcg',
    ],
    outputs: ['beadf', 'ge', 'dcbgef', 'cfeg'],
  },
  {
    inputs: [
      'eafdcb',
      'gcdfbea',
      'eag',
      'dgcba',
      'gacdef',
      'agebd',
      'dbefag',
      'deabf',
      'ge',
      'fgbe',
    ],
    outputs: ['fcbdea', 'bgcdeaf', 'dbgac', 'fagcebd'],
  },
  {
    inputs: [
      'dc',
      'fgebad',
      'ecd',
      'aedcfb',
      'cdga',
      'ebcagd',
      'dfbaecg',
      'adebg',
      'debcg',
      'gbecf',
    ],
    outputs: ['bcegd', 'gcdeb', 'dacg', 'eagdb'],
  },
  {
    inputs: [
      'cad',
      'feabgd',
      'fadegc',
      'bgcdfea',
      'gbcfa',
      'bgcda',
      'bgaced',
      'decb',
      'dc',
      'ebadg',
    ],
    outputs: ['acd', 'adfbge', 'cd', 'dc'],
  },
  {
    inputs: [
      'af',
      'cfbge',
      'fadecg',
      'afbgc',
      'dbaf',
      'gbdfac',
      'bdgeacf',
      'dbcga',
      'cfa',
      'gebcda',
    ],
    outputs: ['fa', 'dabcg', 'dafb', 'gbceda'],
  },
  {
    inputs: [
      'fbgdea',
      'gcefa',
      'agfdb',
      'fecdba',
      'egbd',
      'fdgea',
      'de',
      'bagfcd',
      'gdcbafe',
      'dae',
    ],
    outputs: ['ed', 'eda', 'abdefc', 'fadgeb'],
  },
  {
    inputs: [
      'fdbcga',
      'fdbae',
      'bfa',
      'adfcge',
      'gcbfaed',
      'bfeg',
      'fdage',
      'eacbd',
      'fgbaed',
      'fb',
    ],
    outputs: ['bdcfage', 'fbeg', 'eadfbg', 'gbef'],
  },
  {
    inputs: [
      'cfdbga',
      'fdeab',
      'gefbad',
      'bcaefd',
      'egad',
      'fdaegbc',
      'ag',
      'gcefb',
      'afg',
      'agefb',
    ],
    outputs: ['abfgecd', 'egda', 'bgcfe', 'adefb'],
  },
  {
    inputs: [
      'fbeda',
      'ae',
      'dae',
      'bdgfe',
      'gcadbf',
      'beac',
      'fedabc',
      'badfc',
      'ceagfd',
      'dgcbafe',
    ],
    outputs: ['bfcad', 'gfabdc', 'aed', 'fbdac'],
  },
  {
    inputs: [
      'fgcaed',
      'bagcef',
      'bdfc',
      'edabg',
      'efacd',
      'ebcadf',
      'fb',
      'afb',
      'abefd',
      'agfbdce',
    ],
    outputs: ['cfdb', 'fb', 'abf', 'abf'],
  },
  {
    inputs: [
      'fed',
      'bfaedc',
      'fceab',
      'edabg',
      'bfdea',
      'ecdagf',
      'begfdac',
      'df',
      'fceabg',
      'bfcd',
    ],
    outputs: ['cebgfa', 'df', 'eagbd', 'gafced'],
  },
  {
    inputs: [
      'egfdc',
      'fcg',
      'cadg',
      'dfebc',
      'dfebcga',
      'cg',
      'dgabef',
      'ebgacf',
      'dfgea',
      'gcfade',
    ],
    outputs: ['fbedc', 'gcfed', 'dcag', 'fgc'],
  },
  {
    inputs: [
      'fcbde',
      'fbeacgd',
      'afedb',
      'da',
      'fcegda',
      'dabg',
      'ebgaf',
      'dgfaeb',
      'dea',
      'febagc',
    ],
    outputs: ['da', 'bfdce', 'egfacb', 'ad'],
  },
  {
    inputs: [
      'fcdeg',
      'cdbe',
      'fgcab',
      'dceagf',
      'febcg',
      'eb',
      'cebdgf',
      'geb',
      'edfgab',
      'dbgcaef',
    ],
    outputs: ['abgcfed', 'bdec', 'gdcfe', 'cfgdbe'],
  },
  {
    inputs: [
      'degfb',
      'ebdacf',
      'edbfcg',
      'agdfce',
      'dbf',
      'bd',
      'bgcd',
      'dgfce',
      'gfdcbae',
      'abegf',
    ],
    outputs: ['gebfcd', 'fgeab', 'gecdfb', 'gdafcbe'],
  },
  {
    inputs: [
      'egacd',
      'abedg',
      'decfgba',
      'dagceb',
      'ca',
      'cabe',
      'cag',
      'dagfcb',
      'badfeg',
      'cegfd',
    ],
    outputs: ['gca', 'caeb', 'cfgde', 'ca'],
  },
  {
    inputs: [
      'gfa',
      'ebafd',
      'fg',
      'gafdbec',
      'gaecfb',
      'gbdfa',
      'edfg',
      'gaedbf',
      'bdgca',
      'ecadfb',
    ],
    outputs: ['fbagec', 'fecabd', 'caegbf', 'fg'],
  },
  {
    inputs: [
      'dfgce',
      'cgfbe',
      'cefad',
      'bfdace',
      'fcaged',
      'cdg',
      'badceg',
      'fdceagb',
      'dg',
      'afdg',
    ],
    outputs: ['gcfbe', 'dg', 'gadf', 'edfabc'],
  },
  {
    inputs: [
      'dfgbc',
      'cbfeda',
      'bdgcfe',
      'fdb',
      'efbg',
      'bf',
      'gcedb',
      'fdaecgb',
      'gdecba',
      'fgadc',
    ],
    outputs: ['bgdafec', 'bgcde', 'fbgdc', 'agdfc'],
  },
  {
    inputs: [
      'fgecd',
      'dbegfac',
      'adbfgc',
      'fa',
      'bdcage',
      'acegb',
      'eacgf',
      'efab',
      'fca',
      'fceabg',
    ],
    outputs: ['gafce', 'af', 'gdcbea', 'af'],
  },
  {
    inputs: [
      'fgdacb',
      'fbdec',
      'adb',
      'gfda',
      'acbdegf',
      'edbcga',
      'cfgba',
      'da',
      'cbgefa',
      'cadfb',
    ],
    outputs: ['gbcfea', 'bgcfda', 'da', 'dab'],
  },
  {
    inputs: [
      'fbcdg',
      'abfcdg',
      'cfegbda',
      'ed',
      'dbcaef',
      'gedcfb',
      'aecgb',
      'dcegb',
      'ced',
      'egdf',
    ],
    outputs: ['cabfgde', 'egcdfb', 'fbcade', 'dgcfab'],
  },
  {
    inputs: [
      'dbec',
      'fcd',
      'cegbdf',
      'dc',
      'fdacgeb',
      'abdfg',
      'baefcg',
      'gbfcd',
      'dafgce',
      'gfbec',
    ],
    outputs: ['dcf', 'cfd', 'fcd', 'agefcb'],
  },
  {
    inputs: [
      'fcdeg',
      'gdefb',
      'cfgadbe',
      'fb',
      'bef',
      'bfcg',
      'edfacb',
      'fecdgb',
      'gcdfea',
      'gadeb',
    ],
    outputs: ['efb', 'feb', 'fbcg', 'dabge'],
  },
  {
    inputs: [
      'acebd',
      'dacfg',
      'bdf',
      'agdcbfe',
      'gcafdb',
      'fcegad',
      'afgdbe',
      'bcfg',
      'bfcad',
      'bf',
    ],
    outputs: ['dbf', 'bdaec', 'bf', 'febacdg'],
  },
  {
    inputs: [
      'acdegf',
      'bdfa',
      'afdebg',
      'febcga',
      'gaefb',
      'fd',
      'fed',
      'dgefcab',
      'bedgf',
      'edbcg',
    ],
    outputs: ['efgdab', 'aecdgf', 'cedgbfa', 'def'],
  },
  {
    inputs: [
      'ecdfabg',
      'dfge',
      'cedfba',
      'fcadgb',
      'fgabd',
      'ebgfad',
      'fea',
      'egafb',
      'bcgae',
      'ef',
    ],
    outputs: ['efgdbca', 'eagcfdb', 'defg', 'bfgda'],
  },
  {
    inputs: [
      'efacgd',
      'bfda',
      'bcadg',
      'gab',
      'gbceadf',
      'ab',
      'cfbdga',
      'gadfc',
      'bcgfae',
      'dgbec',
    ],
    outputs: ['fgecad', 'dbaf', 'ba', 'abfgdec'],
  },
  {
    inputs: [
      'bcgaed',
      'fbgc',
      'edcfg',
      'dgbecf',
      'fgdae',
      'dgc',
      'cg',
      'abdcef',
      'gfcbdea',
      'ebfdc',
    ],
    outputs: ['cg', 'cdfeb', 'cg', 'edbcfag'],
  },
  {
    inputs: [
      'cagb',
      'fgcdeab',
      'gdebaf',
      'fcegd',
      'ecabfd',
      'acfeg',
      'ag',
      'afceb',
      'fga',
      'acgbfe',
    ],
    outputs: ['ga', 'agf', 'bcadfe', 'fag'],
  },
  {
    inputs: [
      'fbgde',
      'efbagc',
      'ecgd',
      'efdgabc',
      'ebdcf',
      'fdcgbe',
      'abfdg',
      'fcbead',
      'egb',
      'eg',
    ],
    outputs: ['dcge', 'cedbgf', 'fbgad', 'acegfbd'],
  },
  {
    inputs: [
      'febadcg',
      'cfdbge',
      'bgcef',
      'gecd',
      'ed',
      'gbdaf',
      'bfdeg',
      'deb',
      'gfabce',
      'fcbead',
    ],
    outputs: ['efdbca', 'ed', 'fgcbe', 'cebdaf'],
  },
  {
    inputs: [
      'eagbc',
      'cgde',
      'cafbg',
      'abdge',
      'fbdgae',
      'gacedb',
      'aec',
      'ec',
      'acefbgd',
      'abcefd',
    ],
    outputs: ['bgacf', 'cgbfeda', 'agbed', 'dgec'],
  },
  {
    inputs: [
      'efgbdca',
      'gfdb',
      'cadbfg',
      'dag',
      'dg',
      'degfac',
      'bcdaef',
      'gdacb',
      'bfcad',
      'agebc',
    ],
    outputs: ['gda', 'dfagecb', 'gcfdea', 'dag'],
  },
  {
    inputs: [
      'gefab',
      'bfde',
      'acbfgde',
      'gfdac',
      'ebfgad',
      'bfgeca',
      'aegbcd',
      'eda',
      'gfade',
      'de',
    ],
    outputs: ['gafbce', 'gcfeabd', 'aefgd', 'fgbcae'],
  },
  {
    inputs: [
      'gaecfb',
      'cdebgf',
      'fec',
      'ebcafgd',
      'bgecad',
      'cf',
      'debgc',
      'bfead',
      'ebfdc',
      'cgdf',
    ],
    outputs: ['cdbfe', 'gfcd', 'egbdca', 'edfcgb'],
  },
  {
    inputs: [
      'cfdeba',
      'bfgd',
      'gcedfa',
      'gbdae',
      'dgefcab',
      'cbega',
      'dg',
      'febadg',
      'agd',
      'bdaef',
    ],
    outputs: ['dfgb', 'adg', 'gecdfa', 'fcebda'],
  },
  {
    inputs: [
      'dea',
      'bgdeaf',
      'da',
      'befdc',
      'gdcfaeb',
      'ecdbga',
      'abecd',
      'gacd',
      'bgafce',
      'eagcb',
    ],
    outputs: ['aedcb', 'facebg', 'abfecdg', 'bagefdc'],
  },
  {
    inputs: [
      'gcebf',
      'dfbae',
      'dbgcfe',
      'egdc',
      'dgebcaf',
      'febcd',
      'bcd',
      'cagfeb',
      'fdgcba',
      'dc',
    ],
    outputs: ['bcd', 'efcbd', 'daefb', 'agbdfce'],
  },
  {
    inputs: [
      'fa',
      'acged',
      'bdfec',
      'afeg',
      'gcfadb',
      'bfdagce',
      'ecgafd',
      'caf',
      'acdfe',
      'dgaecb',
    ],
    outputs: ['debfc', 'af', 'afge', 'adegc'],
  },
  {
    inputs: [
      'bacfdg',
      'fadbe',
      'egbdfc',
      'ba',
      'bage',
      'acefd',
      'baf',
      'bgdafe',
      'fgebd',
      'gdacbef',
    ],
    outputs: ['dbfage', 'bgedf', 'aedgbf', 'acedf'],
  },
  {
    inputs: [
      'acgb',
      'dgcbfa',
      'dba',
      'edgbfac',
      'acdefb',
      'begdf',
      'bdgfa',
      'dceafg',
      'dcagf',
      'ba',
    ],
    outputs: ['abd', 'dfbge', 'abd', 'gacb'],
  },
  {
    inputs: [
      'gcdea',
      'gc',
      'agfdce',
      'egdfa',
      'egcf',
      'fbeagd',
      'aecbd',
      'dgc',
      'fcebgad',
      'cagfbd',
    ],
    outputs: ['acebd', 'egcf', 'defag', 'gfadceb'],
  },
  {
    inputs: [
      'fab',
      'begadc',
      'ebcad',
      'dfbea',
      'gfcdab',
      'acdfgbe',
      'fa',
      'fedgb',
      'adcfbe',
      'feca',
    ],
    outputs: ['cbgead', 'bfcdega', 'fba', 'gbadce'],
  },
  {
    inputs: [
      'gb',
      'efcagd',
      'fgcad',
      'cfbg',
      'bedca',
      'abg',
      'fcgbda',
      'dgbcafe',
      'acbgd',
      'bdafeg',
    ],
    outputs: ['abcdgf', 'bcgf', 'cgfb', 'bg'],
  },
  {
    inputs: [
      'fbcagd',
      'fcdae',
      'beacgf',
      'gf',
      'agf',
      'baecdg',
      'fecag',
      'bgfe',
      'cagdbef',
      'gbcea',
    ],
    outputs: ['edbagfc', 'ebfg', 'gebf', 'bgcae'],
  },
  {
    inputs: [
      'cdgfea',
      'bdeacf',
      'aefcgb',
      'dbca',
      'beafc',
      'bcgdefa',
      'ebdgf',
      'ad',
      'defab',
      'ade',
    ],
    outputs: ['dbcgefa', 'da', 'ade', 'bacd'],
  },
  {
    inputs: [
      'bcgaedf',
      'badecg',
      'cfegb',
      'afceg',
      'dcbf',
      'egdbfa',
      'gcedb',
      'gbf',
      'bf',
      'fgcdbe',
    ],
    outputs: ['bagfed', 'bdagfe', 'fdbc', 'gefcbd'],
  },
  {
    inputs: [
      'cegba',
      'bgeda',
      'cgefa',
      'cbde',
      'fegadb',
      'dagcbe',
      'acfgdb',
      'cb',
      'cbg',
      'ecbdafg',
    ],
    outputs: ['cdegabf', 'ebgda', 'bfgade', 'ebgac'],
  },
  {
    inputs: [
      'afbdg',
      'gdabec',
      'gcafdeb',
      'fc',
      'cfdeba',
      'bcf',
      'fgebdc',
      'cefg',
      'gcdbf',
      'ecdbg',
    ],
    outputs: ['fecg', 'cdbefg', 'gdbfc', 'gfce'],
  },
  {
    inputs: [
      'bgdfa',
      'egbf',
      'bcdgfa',
      'fe',
      'dfcbea',
      'aef',
      'feadgb',
      'edcag',
      'dagef',
      'afdcegb',
    ],
    outputs: ['fea', 'cbedfa', 'acdfgeb', 'dfgeab'],
  },
  {
    inputs: [
      'eacgfd',
      'caegdb',
      'gbfecad',
      'bdfce',
      'edcfa',
      'dgaf',
      'fea',
      'fa',
      'egdac',
      'aegbcf',
    ],
    outputs: ['af', 'fa', 'edbcf', 'gdeacbf'],
  },
  {
    inputs: [
      'baefg',
      'fedabcg',
      'gbfac',
      'gacbfe',
      'cb',
      'dfageb',
      'dcfag',
      'cgb',
      'bcea',
      'cfdegb',
    ],
    outputs: ['cabe', 'eabc', 'gfacd', 'fgdcabe'],
  },
  {
    inputs: [
      'fgdeac',
      'cgd',
      'ebdfga',
      'agefdbc',
      'bfcegd',
      'cdgbf',
      'cd',
      'cfabg',
      'dceb',
      'befgd',
    ],
    outputs: ['cgd', 'cfgab', 'fdgeb', 'efbgd'],
  },
  {
    inputs: [
      'aedgbf',
      'cgebda',
      'dbcagf',
      'gbf',
      'gbefd',
      'gdecf',
      'gdfabec',
      'fb',
      'eabdg',
      'feab',
    ],
    outputs: ['bf', 'fbea', 'cefdagb', 'adgbe'],
  },
  {
    inputs: [
      'fcgea',
      'fbgedca',
      'gbecfa',
      'efbadc',
      'efgd',
      'fcagd',
      'df',
      'cdfaeg',
      'fdc',
      'acgdb',
    ],
    outputs: ['efgac', 'fcd', 'dfceba', 'fegac'],
  },
  {
    inputs: [
      'egdfac',
      'cab',
      'cadbf',
      'gbdaf',
      'bc',
      'eadcf',
      'dcebagf',
      'dbecag',
      'fbdace',
      'cebf',
    ],
    outputs: ['cedabfg', 'cgbaed', 'bc', 'efacbdg'],
  },
  {
    inputs: [
      'be',
      'abcged',
      'afcgb',
      'ebg',
      'bgefc',
      'gebfcd',
      'cgefd',
      'efdb',
      'gdeafc',
      'daecgbf',
    ],
    outputs: ['gabedc', 'dbeafcg', 'debf', 'febcadg'],
  },
  {
    inputs: [
      'dgebafc',
      'cefdbg',
      'db',
      'edfb',
      'fcgdb',
      'fdceg',
      'dgecfa',
      'bdc',
      'abcfg',
      'baecdg',
    ],
    outputs: ['fegdca', 'baecdfg', 'bcd', 'bd'],
  },
  {
    inputs: [
      'fbgead',
      'cfab',
      'cdbgefa',
      'agcbdf',
      'aedgc',
      'fgcbd',
      'fa',
      'fagcd',
      'ecgbdf',
      'gaf',
    ],
    outputs: ['adgcebf', 'gaf', 'gaf', 'af'],
  },
  {
    inputs: [
      'debagfc',
      'eb',
      'fcedba',
      'ebc',
      'cgdab',
      'efdgac',
      'befa',
      'eadcf',
      'edabc',
      'gdbefc',
    ],
    outputs: ['bcdagfe', 'fbae', 'ecadb', 'eabf'],
  },
  {
    inputs: [
      'gaedcb',
      'bfcgd',
      'bcegf',
      'bagdcf',
      'fd',
      'aedfgbc',
      'bfd',
      'cbdga',
      'cabefd',
      'adfg',
    ],
    outputs: ['ecfbda', 'cbfgda', 'cfbadg', 'fbgcd'],
  },
  {
    inputs: [
      'agdcfbe',
      'bcfega',
      'cbeag',
      'ge',
      'dacfeb',
      'facged',
      'bcaef',
      'gbdac',
      'gce',
      'efbg',
    ],
    outputs: ['feabc', 'acfbdeg', 'aefbc', 'gce'],
  },
  {
    inputs: [
      'febcdg',
      'egdacb',
      'bedcf',
      'debfacg',
      'abdfce',
      'ba',
      'bae',
      'fbeda',
      'gdfea',
      'acfb',
    ],
    outputs: ['eadbf', 'ab', 'ab', 'eab'],
  },
  {
    inputs: [
      'cdfbg',
      'dfbcae',
      'dcabe',
      'egba',
      'ag',
      'cgdfea',
      'abdcg',
      'aefcdgb',
      'cga',
      'decagb',
    ],
    outputs: ['defabc', 'edacb', 'cbfgd', 'ag'],
  },
  {
    inputs: [
      'fgac',
      'dfgec',
      'eag',
      'cfbdge',
      'bacde',
      'ag',
      'abdgef',
      'bagfdec',
      'dcgfae',
      'agcde',
    ],
    outputs: ['aecbdgf', 'gcaf', 'efcgd', 'befcdg'],
  },
  {
    inputs: [
      'de',
      'gecad',
      'fbcgae',
      'gcafd',
      'dge',
      'edfbcg',
      'eadb',
      'eacfdbg',
      'bcedag',
      'acbge',
    ],
    outputs: ['gabce', 'fcegba', 'bgfcead', 'ed'],
  },
  {
    inputs: [
      'gbacd',
      'dbefcg',
      'fdcgae',
      'edgca',
      'afdeg',
      'aecf',
      'egc',
      'gfaedb',
      'dcfagbe',
      'ce',
    ],
    outputs: ['feac', 'acegd', 'caefbdg', 'aecf'],
  },
  {
    inputs: [
      'egacbd',
      'aedbc',
      'dagbc',
      'fcdagb',
      'ec',
      'bacefdg',
      'ace',
      'dcge',
      'ecfagb',
      'febda',
    ],
    outputs: ['afecgb', 'fgdbac', 'bcade', 'cea'],
  },
  {
    inputs: [
      'ceadgb',
      'cgaedf',
      'bfdge',
      'cfg',
      'cf',
      'fdgbc',
      'dgabc',
      'cfdabg',
      'gdcebaf',
      'bacf',
    ],
    outputs: ['gebdf', 'fdeacg', 'dafbgec', 'cgf'],
  },
  {
    inputs: [
      'bgfda',
      'gdcfae',
      'afce',
      'bfecgd',
      'ac',
      'acdfg',
      'afebdgc',
      'dgefc',
      'bdcaeg',
      'cag',
    ],
    outputs: ['gdbfec', 'gcedf', 'gfdaceb', 'cegdab'],
  },
  {
    inputs: [
      'fa',
      'fgeabdc',
      'bfga',
      'faedb',
      'fad',
      'ebgdfa',
      'daceb',
      'fgbcde',
      'fgdeb',
      'dafcge',
    ],
    outputs: ['efdab', 'gcdfeb', 'fa', 'gabf'],
  },
  {
    inputs: [
      'ebfc',
      'fb',
      'aedbgc',
      'ebagdf',
      'fab',
      'cgfeab',
      'gcdfeba',
      'acbeg',
      'abcfg',
      'gfdca',
    ],
    outputs: ['gbfac', 'bgfeac', 'bfa', 'bcfga'],
  },
  {
    inputs: [
      'fagdec',
      'gadebc',
      'cg',
      'cabfegd',
      'agdfb',
      'cbge',
      'dbeac',
      'cdfabe',
      'adcbg',
      'cgd',
    ],
    outputs: ['acgbed', 'dgfeabc', 'fdeacb', 'dgbacef'],
  },
  {
    inputs: [
      'fgbdc',
      'gbedaf',
      'bdgaf',
      'dfc',
      'cbfadg',
      'gfceb',
      'degcfa',
      'dc',
      'bacd',
      'gbafcde',
    ],
    outputs: ['dcf', 'egfdca', 'cd', 'cdegaf'],
  },
  {
    inputs: [
      'fcb',
      'aebf',
      'bf',
      'cafgb',
      'efgabc',
      'cgadbe',
      'egbadfc',
      'egbca',
      'gcfebd',
      'acdgf',
    ],
    outputs: ['beacgfd', 'gebfcd', 'dfbgec', 'bf'],
  },
  {
    inputs: [
      'bfgcd',
      'deb',
      'bfacdg',
      'ed',
      'fcebgd',
      'baefg',
      'dbaecfg',
      'efdc',
      'dabecg',
      'fdgbe',
    ],
    outputs: ['de', 'gebaf', 'dbcgfe', 'bde'],
  },
  {
    inputs: [
      'facgdbe',
      'gda',
      'ebdfag',
      'gabdf',
      'da',
      'cagfeb',
      'gebaf',
      'deaf',
      'dbagec',
      'dcfbg',
    ],
    outputs: ['egfba', 'dgebca', 'aefd', 'cgdbf'],
  },
  {
    inputs: [
      'deabg',
      'eg',
      'gdfacb',
      'bdfea',
      'egd',
      'gebfdca',
      'ecdgab',
      'acge',
      'dacbg',
      'cefgbd',
    ],
    outputs: ['eg', 'dgcbef', 'agcdb', 'fadbceg'],
  },
  {
    inputs: [
      'cafbged',
      'feacb',
      'gbafd',
      'dc',
      'gfdc',
      'agdcbf',
      'fcabd',
      'deabgf',
      'cad',
      'acgedb',
    ],
    outputs: ['fdcba', 'egbfdac', 'cad', 'dca'],
  },
  {
    inputs: [
      'dfagce',
      'fbd',
      'eabdfc',
      'gdfeb',
      'ebgfa',
      'dfabcge',
      'fdgce',
      'cedfbg',
      'bcgd',
      'bd',
    ],
    outputs: ['cdbg', 'agbcefd', 'db', 'db'],
  },
  {
    inputs: [
      'fdagec',
      'fcg',
      'gf',
      'gbace',
      'efbgacd',
      'ecgbfd',
      'dfcea',
      'caefg',
      'dagf',
      'dbecaf',
    ],
    outputs: ['acdegfb', 'fg', 'gbdfaec', 'fadg'],
  },
  {
    inputs: [
      'edfag',
      'bgfced',
      'dga',
      'ag',
      'cfbgdea',
      'bfdcag',
      'bfged',
      'decfa',
      'afedbg',
      'bgae',
    ],
    outputs: ['abeg', 'dgaef', 'ag', 'edfgb'],
  },
  {
    inputs: [
      'dcaegb',
      'fageb',
      'cdga',
      'begda',
      'adbce',
      'gd',
      'dge',
      'gbecafd',
      'cabfed',
      'cgfebd',
    ],
    outputs: ['gdaebc', 'ged', 'egd', 'dcga'],
  },
  {
    inputs: [
      'cfb',
      'agebfc',
      'fegb',
      'fb',
      'adcef',
      'afbec',
      'ebgdca',
      'bafdgc',
      'gbcea',
      'fdbeagc',
    ],
    outputs: ['ebfg', 'gabce', 'fbc', 'agfdceb'],
  },
  {
    inputs: [
      'fdcega',
      'cbgfea',
      'febg',
      'agdebfc',
      'cfe',
      'afecb',
      'gbcae',
      'ef',
      'bcdfa',
      'acgedb',
    ],
    outputs: ['fbgdeac', 'egbf', 'acfgeb', 'bfge'],
  },
  {
    inputs: [
      'fbadge',
      'dfgebc',
      'fbgacde',
      'bg',
      'fdage',
      'afdcge',
      'cedba',
      'agbf',
      'bge',
      'dgbea',
    ],
    outputs: ['adgbe', 'fgba', 'gabf', 'fceagd'],
  },
  {
    inputs: [
      'cfbda',
      'bgedca',
      'fgdcba',
      'abcfe',
      'dc',
      'agbfd',
      'dbc',
      'fdgc',
      'facbged',
      'dagfeb',
    ],
    outputs: ['cd', 'fbcda', 'fdcab', 'fdgc'],
  },
  {
    inputs: [
      'cdefa',
      'fbgdce',
      'aebdg',
      'geacd',
      'ebcdgfa',
      'gc',
      'cdg',
      'baegdc',
      'febdag',
      'gbac',
    ],
    outputs: ['fdeca', 'cg', 'dgfbcae', 'bcgfde'],
  },
  {
    inputs: [
      'gcadeb',
      'ef',
      'ecbfga',
      'acbgfed',
      'fbdga',
      'bcade',
      'dafcbe',
      'dcfe',
      'deabf',
      'feb',
    ],
    outputs: ['fdegacb', 'agdbf', 'fgbedac', 'fcdbaeg'],
  },
  {
    inputs: [
      'adgc',
      'fac',
      'ca',
      'gdfcae',
      'cfdegb',
      'gcdef',
      'adcfbe',
      'dgefcba',
      'cagef',
      'abgef',
    ],
    outputs: ['gcadbfe', 'feabdc', 'cdefg', 'bgdeafc'],
  },
  {
    inputs: [
      'cfdeba',
      'dega',
      'fga',
      'gadfec',
      'cdfabeg',
      'aecbfg',
      'cbdfg',
      'ag',
      'faedc',
      'dfcag',
    ],
    outputs: ['ag', 'ga', 'acfed', 'cebfad'],
  },
  {
    inputs: [
      'efcgb',
      'feagdc',
      'gdfbea',
      'fadc',
      'ac',
      'cea',
      'gadbfce',
      'cfgae',
      'aedgbc',
      'geafd',
    ],
    outputs: ['fcgeabd', 'cafeg', 'cbadge', 'ca'],
  },
  {
    inputs: [
      'ebfda',
      'cfgbea',
      'cgdbef',
      'fbadgec',
      'dgcb',
      'cedfga',
      'dg',
      'fdbeg',
      'efcgb',
      'gfd',
    ],
    outputs: ['fgdeb', 'bfgcde', 'ebfdg', 'dg'],
  },
  {
    inputs: [
      'dcafg',
      'facgdb',
      'bgfa',
      'dbacf',
      'ba',
      'gdcefa',
      'ecfdb',
      'cfegdba',
      'bac',
      'acedbg',
    ],
    outputs: ['gcbdaf', 'fbadc', 'begdac', 'dgcbaf'],
  },
  {
    inputs: [
      'eagf',
      'agedbcf',
      'acdegb',
      'abg',
      'gcfba',
      'fcegb',
      'befgcd',
      'fbcda',
      'ag',
      'ebcfag',
    ],
    outputs: ['dbcegfa', 'bfecg', 'cafdebg', 'faeg'],
  },
  {
    inputs: [
      'fbgcd',
      'cba',
      'fgacdb',
      'gabcdef',
      'fbgdec',
      'gdabc',
      'gacf',
      'bafdec',
      'begad',
      'ac',
    ],
    outputs: ['eacbdf', 'badge', 'acb', 'becfad'],
  },
  {
    inputs: [
      'eacbd',
      'dabfec',
      'dbgfeac',
      'ag',
      'eagdb',
      'fcdbag',
      'bga',
      'agec',
      'dbfge',
      'bacged',
    ],
    outputs: ['agecdb', 'bag', 'gebcdaf', 'cdbea'],
  },
  {
    inputs: [
      'bfgcd',
      'bcdegfa',
      'fdabgc',
      'da',
      'efgca',
      'cfagd',
      'efbdca',
      'cda',
      'dgfecb',
      'bgda',
    ],
    outputs: ['acdebf', 'badfcg', 'abdg', 'cafgd'],
  },
  {
    inputs: [
      'efcbgd',
      'cadefg',
      'cfegd',
      'dcgba',
      'cafedgb',
      'cagfd',
      'gaf',
      'acef',
      'fa',
      'bedafg',
    ],
    outputs: ['agf', 'fcedg', 'gefdcb', 'cfdge'],
  },
  {
    inputs: [
      'afdceg',
      'dcaf',
      'fd',
      'dfg',
      'aefgc',
      'gdbecf',
      'cafbdeg',
      'dbage',
      'ecagfb',
      'deafg',
    ],
    outputs: ['adefgc', 'bfdecga', 'fdg', 'cefag'],
  },
  {
    inputs: [
      'bfdacg',
      'dagbf',
      'abdefcg',
      'acfg',
      'fbcda',
      'beafdc',
      'egdab',
      'cfdegb',
      'gfd',
      'gf',
    ],
    outputs: ['bcafgd', 'efgcabd', 'cfga', 'dcaegfb'],
  },
  {
    inputs: [
      'dbage',
      'dfagbe',
      'cadfeb',
      'gfeb',
      'bae',
      'fabgdc',
      'be',
      'bafdg',
      'cdgea',
      'bgdfaec',
    ],
    outputs: ['fedacbg', 'eb', 'dfcbea', 'eab'],
  },
  {
    inputs: [
      'gebfd',
      'cfedga',
      'begfa',
      'dagbfc',
      'fgeadcb',
      'ecdgbf',
      'bced',
      'edfgc',
      'dgb',
      'db',
    ],
    outputs: ['dbec', 'gadcfb', 'db', 'aefbg'],
  },
  {
    inputs: [
      'dbcg',
      'fbagc',
      'bcf',
      'bc',
      'cdaebgf',
      'aegbdf',
      'faecg',
      'fdcaeb',
      'cdafbg',
      'afbgd',
    ],
    outputs: ['adfbg', 'fadebgc', 'dgbafc', 'febagd'],
  },
];
